"""Where the time per box goes: each tick up to the last placement, sorted into
one phase, averaged per placed box, then per seed and per scenario.

usage: python time_breakdown.py <results_dir> [out.md]

Phases (sim time unless noted):
  scan_pause   task_node's 1 s pause after each scan (SCAN_PAUSE_TICKS)
  motion_fast  reference moving at >= 0.05 m/s (transits, set by task_node's caps)
  motion_slow  reference moving at < 0.05 m/s (touch-down 0.02, pushes 0.05, blends)
  converging   reference stopped, arm not yet within 5 mm / 0.05 rad/s of it
  at_goal      reference stopped, arm there: settle dwell, grasp/release, decisions
  hold         supervisor hold (obstacle scenario)
  scan_wall    wall time of the scans themselves (the sim is paused meanwhile)
Only converging is the controller's doing; the rest is set by the task logic,
though faster, better-tracked motion could let task_node raise its speed caps.
"""
import re
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from bench_analyze import load  # noqa: E402

DT = 0.02
FAST_MPS = 0.05
STOPPED_MPS = 0.005
AT_GOAL_M = 0.005
AT_REST_QDOT = 0.05
PAUSE_STATES = (2, 6)
SCAN_STATES = (1, 5)
PHASES = ["motion_fast", "motion_slow", "converging", "at_goal", "scan_pause", "hold", "scan_wall"]


def breakdown(run):
    log = (run / "launch.log").read_text(errors="replace")
    placed = [float(t) for t in re.findall(r"\[(\d+\.\d+)\] \[mujoco_sim_node\]: placed cbox_", log)]
    if not placed:
        return None
    task, mpc, sim = load(run / "task.csv"), load(run / "mpc.csv"), load(run / "sim.csv")
    ee = dict(zip(mpc["state_step"].astype(int), mpc["ee_err"]))
    qd = dict(zip(sim["step"].astype(int), sim["qdot_norm"]))
    keep = task["wall_t"] <= placed[-1]
    wall_dt = np.diff(task["wall_t"], append=task["wall_t"][-1])
    out = defaultdict(float)
    for i in np.where(keep)[0]:
        st, v, k = int(task["state"][i]), task["ref_speed"][i], int(task["step"][i])
        if st in SCAN_STATES:
            out["scan_wall"] += wall_dt[i]
            continue
        if task["hold"][i]:
            ph = "hold"
        elif st in PAUSE_STATES:
            ph = "scan_pause"
        elif v >= FAST_MPS:
            ph = "motion_fast"
        elif v > STOPPED_MPS:
            ph = "motion_slow"
        elif ee.get(k, 0.0) > AT_GOAL_M or qd.get(k, 0.0) > AT_REST_QDOT:
            ph = "converging"
        else:
            ph = "at_goal"
        out[ph] += DT
    return {p: out[p] / len(placed) for p in PHASES}


def main():
    root = Path(sys.argv[1])
    per = defaultdict(lambda: defaultdict(list))  # scenario -> seed -> [dicts]
    for run in sorted((root / "runs").iterdir()):
        if not (run / "task.csv").exists():
            continue
        b = breakdown(run)
        if b is None:
            continue
        scen = re.sub(r"_s\d+.*$", "", run.name)
        per[scen][int(re.search(r"_s(\d+)", run.name).group(1))].append(b)
    lines = ["# Time per placed box, by phase [s]", "",
             "Generated by `scripts/dev/time_breakdown.py`. Median over seeds of each seed's mean; "
             "share of the sim-time total in brackets. `scan_wall` is wall time (the sim is paused).", "",
             "| phase | " + " | ".join(sorted(per)) + " |", "|---|" + "---|" * len(per)]
    med = {}
    for scen in sorted(per):
        seeds = {s: {p: np.mean([r[p] for r in rs]) for p in PHASES} for s, rs in per[scen].items()}
        med[scen] = {p: float(np.median([v[p] for v in seeds.values()])) for p in PHASES}
    for p in PHASES:
        cells = []
        for scen in sorted(per):
            total = sum(med[scen][q] for q in PHASES if q != "scan_wall")
            share = "" if p == "scan_wall" else f" ({100 * med[scen][p] / total:.0f}%)"
            cells.append(f"{med[scen][p]:.2f}{share}")
        lines.append(f"| {p} | " + " | ".join(cells) + " |")
    lines.append("| **sim total** | " + " | ".join(
        f"{sum(med[s][q] for q in PHASES if q != 'scan_wall'):.2f}" for s in sorted(per)) + " |")
    text = "\n".join(lines) + "\n"
    print(text)
    if len(sys.argv) > 2:
        Path(sys.argv[2]).write_text(text)


if __name__ == "__main__":
    main()
